# Generated by Django 5.0.5 on 2024-05-16 20:15

import apps.core.utils.upload_file
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Last Update')),
                ('name', models.CharField(max_length=255)),
                ('name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
                ('mass', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('portion_for', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(max_length=255, upload_to=apps.core.utils.upload_file.instance_file_directory_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_category.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
